### ISSUE TITLE
Why you using RAM Disk for /usr/local?

### ISSUE THREAD

**Issue by antonydevanchi** [alexey-lysiuk/tools#2]
Hi @alexey-lysiuk,

Context: [/scripts/system/image_usr_local](https://github.com/alexey-lysiuk/tools/blob/master/scripts/system/image_usr_local)

`sudo hdiutil attach -mountpoint /usr/local usr.local.sparseimage`

Please, link me RTFM or describe reasons for using RAM Disk for /usr/local. I think it made something good with performance, right? But erase any existing content, yeah?  

$5 / answer :)

Thanks!

**Comment by alexey-lysiuk** [comment]
It was used only for installing some libraries without affecting any content on persistent drives.
